when@prod:
    doctrine:
        dbal:
            schema_filter: '~^(?!auth\.|storage\.|realtime\.|graphql_public\.|supabase_functions\.|extensions\.|pgsodium\.|vault\.|net\.).*~'
            url: '%env(resolve:DATABASE_URL)%'
            profiling_collect_backtrace: false
            use_savepoints: true
            server_version: '15'
            mapping_types:
                regclass: string
                _text: text
                _varchar: string
                _int4: integer
                _int8: bigint
                aal_level: string
                factor_type: string
                factor_status: string
                code_challenge_method: string
                one_time_token_type: string
                key_status: string
                key_type: string
                _uuid: guid
                uuid: guid
                hstore: text
                ltree: text
                citext: text