doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
        server_version: '15'
        mapping_types:
            regclass: string
            _text: text
            _varchar: string
            _int4: integer
            _int8: bigint
            aal_level: string
            factor_type: string
            factor_status: string
            code_challenge_method: string
            one_time_token_type: string
            key_status: string
            key_type: string
            _uuid: guid
            uuid: guid
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App